# https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#configuring-the-l10n-yaml-file

arb-dir: lib/core/config/l10n/arb
output-dir: lib/core/config/l10n
# package:flutter_gen を使用しない
# https://docs.flutter.dev/release/breaking-changes/flutter-generate-i10n-source
synthetic-package: false
