# https://dart.dev/tools/pub/pubspec
name: flutter_sandbox
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  # Dart SDK version
  # https://dart.dev/get-dart/archive
  sdk: ^3.8.0

dependencies:
  cloud_firestore:
  cloud_functions:
  envied:
  firebase_analytics:
  firebase_app_check:
  firebase_app_installations:
  firebase_auth:
  firebase_core:
  firebase_crashlytics:
  firebase_data_connect:
  firebase_database:
  firebase_in_app_messaging:
  firebase_performance:
  firebase_remote_config:
  firebase_storage:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_localizations:
    sdk: flutter
  freezed_annotation:
  go_router:
  hooks_riverpod: ^3.0.0-dev.16
  intl:
  logger:
  logging:
  multiple_result:
  responsive_framework:
  riverpod_annotation: ^3.0.0-dev.16
  stack_trace:
  window_manager:

dev_dependencies:
  build_runner:
  # https://pub.dev/documentation/go_router/latest/topics/Type-safe%20routes-topic.html
  build_verify:
  custom_lint:
  envied_generator:
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  go_router_builder:
  integration_test:
    sdk: flutter
  mockito:
  pedantic_mono:
  riverpod_generator: ^3.0.0-dev.16
  riverpod_lint: ^3.0.0-dev.16

flutter:
  uses-material-design: true

  # https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#adding-your-own-localized-messages
  generate: true

  assets:
    - assets/images/
