# https://dart.dev/tools/pub/pubspec
name: flutter_sandbox
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  # Dart SDK version
  # https://dart.dev/get-dart/archive
  sdk: ^3.8.0

dependencies:
  cloud_firestore:
  cloud_functions:
  firebase_analytics:
  firebase_app_check:
  firebase_app_installations:
  firebase_auth:
  firebase_core:
  firebase_crashlytics:
  firebase_data_connect:
  firebase_database:
  firebase_in_app_messaging:
  firebase_performance:
  firebase_remote_config:
  firebase_storage:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
  pedantic_mono:

flutter:
  uses-material-design: true
